### ISSUE TITLE
comentarios avance2

### ISSUE THREAD

**Issue by AliciaMstt** [marialadelbarrio/tareas_curso_bioinfinvrepro#1]
Hola María. Qué bueno que tengan una cuenta en Miztle. Tus avances 2 se ven bien y entiendo lo de las rutas absolutas para las partes que correrás en miztli. Recomendaciones que tendrás que tomar en cuenta para tu entrega final:

1. Los pasos para correr Stacks y cualquier otro software no los quiero en el archivo del proyecto como en tu avance, sino en scripts por separado para cada análisis o grupo de análisis.

2. Si bien tienes que poner rutas absolutas en Miztli, una forma de hacer más reproducible tu trabajo y fácil de seguir es que asignes el path a una variable. Por ejemplo:

```
mypath="/tmpu/pindaro_g/cdm_a/maria/RADcap"

clone_filter -1 $mypath/raw/S_concolor_Pool3.1.fq.gz -2 $mypath/raw/S_concolor_Pool3.2.fq.gz -i gzfastq -o $mypath/filtered -y gzfastq --inline_inline --oligo_len_2 8 &>> $mypath/clonefilter.log
```

De esta forma cualquier persona volviendo a correr un script con ese contenido solo tendría que sustituir "/tmpu/pindaro_g/cdm_a/maria/RADcap" por su propia ruta absoluta.

**Comment by marialadelbarrio** [comment]
Ok, muchas gracias! en los siguientes scripts estoy intentando incluir las rutas (: :100:

**Comment by AliciaMstt** [comment]
Bien
